# - name: Run the equivalent of "apt-get update" as a separate step
#   apt:
#     update_cache: yes

- name: Install packages
  apt:
    pkg: 
      - openjdk-11-jre-headless
      - python3
      - python3-pip

    state: present

- name: Update pip
  pip:
    name:
      - pip
    extra_args: --upgrade
    executable: pip3

- name: Install python modules
  pip:
    name:
      - cryptography
      - kafka-python
      - couchdb
    executable: pip3
    